image: Ubuntu2004  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

test_script:
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-ibank-build-for-testers.jar &
  # -Dselenide.headless=true запустит браузер в невидимом режиме
  # запускаем тест, флаг --info позволяет выводить больше информации
  - ./gradlew test -Dselenide.headless=true --info
on_finish:
  - 7z a build/reports.zip build/reports/
  - appveyor PushArtifact build/reports.zip