image: Ubuntu2004  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

test_script:
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-ibank-build-for-testers.jar echo $! > ./testserver.pid &
  # запускаем тест, флаг --info позволяет выводить больше информации
  # -Dselenide.headless=true запустит браузер в невидимом режиме
  - ./gradlew test -Dselenide.headless=true --tests ru.netology.RunCucumberTest --info
  - kill -TERM $(cat ./testserver.pid)
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-ibank-build-for-testers.jar echo $! > ./testserver.pid &
  # запускаем тест, флаг --info позволяет выводить больше информации
  # -Dselenide.headless=true запустит браузер в невидимом режиме
  - ./gradlew test -Dselenide.headless=true --tests ru.netology.TransferBetweenOwnCardsTest --info
  - - kill -TERM $(cat ./testserver.pid)
on_finish:
  - 7z a build/reports.zip build/reports/
  - appveyor PushArtifact build/reports.zip